name: counter_app
description: Counter demo app implemented with 'reduced' API and 'reduced_statesrebuilder' implementation as an example of the usage of the 'reduced_statesrebuilder' package.
publish_to: 'none' 
version: 0.4.0+5

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  reduced: 0.4.0
#  reduced: 
#    git:
#      url: https://github.com/partmaster/reduced.git
#      ref: v0.4.0
  reduced_statesrebuilder: 
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
